version: '3.9'

services:
  browser:
    image: {{ job_image }}
    command: ["python", "-m", "btrixcloud.swarm.profile_job"]
    configs:
      - btrix_shared_job_config

    secrets:
      - btrix_storages

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    #networks:
    #  - btrix

    deploy:
      #endpoint_mode: dnsrr
      labels:
        btrix.profile: "1"
        btrix.archive: {{ aid }}
        btrix.user: {{ userid }}
        {%- if baseprofile %}
        btrix.baseprofile: "{{ baseprofile }}"
        {%- endif %}

      #mode: replicated-job
      replicas: 1

    environment:
      JOB_ID: "{{ id }}"
      STACK_PREFIX: "browser-"
      STORAGE_PATH: "{{ storage_path }}"
      STORAGE_NAME: "{{ storage_name }}"
      IDLE_TIMEOUT: "60"
      START_URL: "{{ url }}"
      PROFILE_PATH: "{{ profile_path }}"
 

#networks:
#  btrix:
#    external: 
#      name: btrix-cloud-net


configs:
  btrix_shared_job_config:
    external: true

secrets:
  btrix_storages:
    external: true
