version: '3.8'

services:
  backend:
    build: ./backend
    image: ${REGISTRY}webrecorder/browsertrix-backend:latest

    secrets:
      - shared_job_config.yaml

    env_file:
      - ./configs/config.env

    depends_on:
      - minio
      - mongo

# enable to expose backend api container directly
#    ports:
#      - 8000:8000

    environment:
      - CRAWLER_FQDN_SUFFIX=
      - JOB_IMAGE=${REGISTRY}webrecorder/browsertrix-backend:latest

    restart: always

  frontend:
    build: ./frontend
    image: ${REGISTRY}webrecorder/browsertrix-frontend:latest
    ports:
      - 9871:80

    depends_on:
      - backend
      - minio

    environment:
      - BACKEND_HOST=backend
      - CRAWLER_FQDN_SUFFIX=
      - CRAWLER_SVC_SUFFIX=

    restart: always

  mongo:
    image: mongo
    volumes:
      - btrix-mongo-data:/data/db

    env_file:
      - ./configs/config.env

    restart: always

  minio:
    image: minio/minio
    #command: ["server", "/data", "--console-address", ":9001"]

    entrypoint: "/bin/sh"
    # auto-create bucket via existing dir (only for single-node mode)
    command: ["-c", "mkdir -p /data/$$MINIO_BUCKET; /usr/bin/docker-entrypoint.sh server /data --console-address :9001"]

    volumes:
      - btrix-minio-data:/data

    env_file:
      - ./configs/config.env

    restart: always

# enable below to access minio console directly
#    ports:
#      - 9001:9001
#
#    environment:
#      - MINIO_SERVER_URL=http://127.0.0.1:9000

volumes:
  btrix-redis-data:
  btrix-mongo-data:
  btrix-minio-data:

networks:
  default:
    name: btrix-net

secrets:
  shared_job_config.yaml:
    file: ./configs/config.yaml
