{{- if .Values.redis_local }}


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: local-redis
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: local-redis

  replicas: 1
  serviceName: local-redis

  volumeClaimTemplates:
  - metadata:
      name: redis-data
      annotations:
        helm.sh/resource-policy: keep
    spec:
      accessModes:
        - ReadWriteOnce

      resources:
        requests:
          storage: 1Gi

      {{- if .Values.volume_storage_class }}
      storageClassName: {{ .Values.volume_storage_class }}
      {{- end }}

  template:
    metadata:
      labels:
        app: local-redis

    spec:
      containers:
        - name: redis
          image: {{ .Values.redis_image }}
          imagePullPolicy: {{ .Values.redis_pull_policy }}

          args: ["--appendonly", "yes"]
          volumeMounts:
            - name: redis-data
              mountPath: /data
              subPath: redis

          resources:
            limits:
              cpu: {{ .Values.redis_limits_cpu }}
              memory: {{ .Values.redis_limits_memory }}

            requests:
              cpu: {{ .Values.redis_requests_cpu }}
              memory: {{ .Values.redis_requests_memory }}

          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping

---
apiVersion: v1
kind: Service

metadata:
  namespace: {{ .Release.Namespace }}
  name: local-redis
  labels:
    app: local-redis

spec:
  clusterIP: None
  selector:
    app: local-redis

  ports:
    - protocol: TCP
      port: 6379
      name: redis

{{- end }}


